<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CorrectnessTest" tests="4" skipped="0" failures="3" errors="0" timestamp="2019-10-20T20:28:40" hostname="vadzimko.local" time="0.065">
  <properties/>
  <testcase name="testConcurrentRandom" classname="CorrectnessTest" time="0.041">
    <failure message="java.lang.AssertionError: Expected value to be false." type="java.lang.AssertionError">java.lang.AssertionError: Expected value to be false.
	at org.junit.Assert.fail(Assert.java:88)
	at kotlin.test.junit.JUnitAsserter.fail(JUnitSupport.kt:56)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:196)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:206)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.AssertionsKt__AssertionsKt.assertFalse(Assertions.kt:46)
	at kotlin.test.AssertionsKt.assertFalse(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertFalse$default(Assertions.kt:44)
	at kotlin.test.AssertionsKt.assertFalse$default(Unknown Source)
	at CorrectnessTest.testConcurrentRandom(CorrectnessTest.kt:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="testSolutionClass" classname="CorrectnessTest" time="0.005"/>
  <testcase name="testRandom" classname="CorrectnessTest" time="0.013">
    <failure message="java.lang.AssertionError: expected:&lt;0&gt; but was:&lt;600123930&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;0&gt; but was:&lt;600123930&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at CorrectnessTest.verifyRandom(CorrectnessTest.kt:31)
	at CorrectnessTest.testRandom(CorrectnessTest.kt:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="testSimple" classname="CorrectnessTest" time="0.004">
    <failure message="java.lang.AssertionError: expected:&lt;0&gt; but was:&lt;1&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;0&gt; but was:&lt;1&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at CorrectnessTest.testSimple(CorrectnessTest.kt:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <system-out><![CDATA[Thread[Thread-30,5,FailOnTimeoutGroup]: Failed with java.lang.AssertionError: expected:<0> but was:<600123930>
Thread[Thread-31,5,FailOnTimeoutGroup]: Failed with java.lang.AssertionError: expected:<0> but was:<600123930>
Thread[Thread-32,5,FailOnTimeoutGroup]: Failed with java.lang.AssertionError: expected:<0> but was:<600123930>
Thread[Thread-28,5,FailOnTimeoutGroup]: Failed with java.lang.AssertionError: expected:<0> but was:<600123930>
Thread[Thread-29,5,FailOnTimeoutGroup]: Failed with java.lang.AssertionError: expected:<0> but was:<600123930>
]]></system-out>
  <system-err><![CDATA[java.lang.AssertionError: expected:<0> but was:<600123930>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at CorrectnessTest.verifyRandom(CorrectnessTest.kt:31)
	at CorrectnessTest.access$verifyRandom(CorrectnessTest.kt:7)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:40)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:7)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
java.lang.AssertionError: expected:<0> but was:<600123930>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at CorrectnessTest.verifyRandom(CorrectnessTest.kt:31)
	at CorrectnessTest.access$verifyRandom(CorrectnessTest.kt:7)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:40)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:7)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
java.lang.AssertionError: expected:<0> but was:<600123930>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at CorrectnessTest.verifyRandom(CorrectnessTest.kt:31)
	at CorrectnessTest.access$verifyRandom(CorrectnessTest.kt:7)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:40)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:7)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
java.lang.AssertionError: expected:<0> but was:<600123930>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at CorrectnessTest.verifyRandom(CorrectnessTest.kt:31)
	at CorrectnessTest.access$verifyRandom(CorrectnessTest.kt:7)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:40)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:7)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
java.lang.AssertionError: expected:<0> but was:<600123930>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at CorrectnessTest.verifyRandom(CorrectnessTest.kt:31)
	at CorrectnessTest.access$verifyRandom(CorrectnessTest.kt:7)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:40)
	at CorrectnessTest$testConcurrentRandom$$inlined$List$lambda$1.invoke(CorrectnessTest.kt:7)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
]]></system-err>
</testsuite>
